// -------------------------------------------------
//
//
// -------------------------------------------------
//                         Harris Georgiou, 1997.
// -------------------------------------------------



#ifndef     __GAME_DEFS_H__
#define     __GAME_DEFS_H__


/*........... GAME BOARD & STATUS ...........*/

typedef     int         TSize;
                         
#define     gSizeX      (TSize)3
#define     gSizeY      (TSize)3
#define     gSizeZ      (TSize)2


typedef     char        TBoard;

#define     cDefBoardValue      (TBoard)45


typedef     long        TValue;

#define     cDefGameValue       (TValue)0



#endif


